# triggers shall also be defined in Azure DevOps pipeline settings

trigger:
  - none

pr: none

name: $(Date:yyyyMMdd)-$(Hours).$(Minutes)-$(SourceBranch).$(Rev:r)

pool:
  vmImage: ubuntu-latest

stages:
  - stage: production
    displayName: production
    variables:
      - group: prod
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: appservice
        displayName: Swap slots
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureAppServiceManage@0
                  displayName: Swap rc to production
                  inputs:
                    azureSubscription: '$(azureRmServiceConnectionName)'
                    Action: 'Swap Slots'
                    WebAppName: '$(appServiceName)'
                    ResourceGroupName: '$(appServiceRgName)'
                    SourceSlot: '$(appServiceSlotName)'
                    PreserveVnet: true
