version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    read_only: true
    security_opt:
      - no-new-privileges:true
    networks:
      - grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./k6/dashboards:/var/lib/grafana/dashboards
      - ./k6/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./k6/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    cap_drop:
      - ALL

  influxdb:
    image: influxdb:1.8
    read_only: true
    security_opt:
      - no-new-privileges:true
    networks:
      - k6
      - grafana
    environment:
      - INFLUXDB_DB=k6

  k6:
    image: 24hoursmedia/k6-xarch:latest
    read_only: true
    security_opt:
      - no-new-privileges:true
    networks:
      - k6
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6/auto:/auto
    cap_drop:
      - ALL

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.alpine.prod
    networks:
      - k6
    ports:
      - 8080:8080
    environment:
      - SWAGGER_STATS_USERNAME=local
      - SWAGGER_STATS_PASSWORD=local
    user: node
    cap_drop:
      - ALL

networks:
  grafana:
  k6:
