FROM golang:alpine3.17 as builder
WORKDIR $GOPATH/src/go.k6.io/k6
RUN apk add --no-cache --update git
RUN go install go.k6.io/xk6/cmd/xk6@latest
RUN xk6 build --with github.com/grafana/xk6-output-influxdb --output /tmp/k6

FROM alpine:3.17
RUN apk add --no-cache --update ca-certificates
RUN adduser -D k6
COPY --from=builder /tmp/k6 /usr/bin/k6

USER k6
WORKDIR /home/k6
ENTRYPOINT ["k6"]
