#!/usr/bin/env bash

## scan vulnerabilties
npm run sec

## format code
npx pretty-quick --staged

## lint typescript
npx eslint --cache --fix

## lint openapi
npm run lint:spec

## generate tests
npm run portman && git add portman/collection.postman.json
